-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 15:53:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema enrollment_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enrollment_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enrollment_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `enrollment_db` ;

-- -----------------------------------------------------
-- Table `enrollment_db`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enrollment_db`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(100) NULL DEFAULT NULL,
  `course_description` TEXT NULL DEFAULT NULL,
  `credits` INT NULL DEFAULT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enrollment_db`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enrollment_db`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enrollment_db`.`enrolled_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enrollment_db`.`enrolled_subject` (
  `enrollment_id` INT NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(90) NULL DEFAULT NULL,
  `course_name` VARCHAR(100) NULL DEFAULT NULL,
  `student_student_id` INT NOT NULL,
  `course_course_id` INT NOT NULL,
  PRIMARY KEY (`enrollment_id`),
  INDEX `student_id` (`student_name` ASC) VISIBLE,
  INDEX `course_id` (`course_name` ASC) VISIBLE,
  INDEX `fk_enrolled_subject_student_idx` (`student_student_id` ASC) VISIBLE,
  INDEX `fk_enrolled_subject_course1_idx` (`course_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_enrolled_subject_student`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `enrollment_db`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enrolled_subject_course1`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `enrollment_db`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
